### ISSUE TITLE
control ICMP rules created with LoadBalancer type service

### ISSUE THREAD

**Issue by infa-ddeore** [kubernetes/cloud-provider-aws#101]
**What would you like to be added**:
Currently if a k8 service of type `LoadBalancer` is created without `loadBalancerSourceRanges`, it adds 2 SG rules to the loadbalancer SG, one is for the actual service port which is expected. But the other SG rule is also added that opens ICMP rule for all which comes into security team's radar. 

Manually editing SG is a short fix, if the same k8 service is re-applied then the ICMP SG rule appears back.

**Why is this needed**:
Security risk

/kind feature

**Comment by TBBle** [comment]
Are you referring to the [Path MTU Discovery (Type 3, Code 4)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html#path_mtu_discovery) rule? That's pretty important for the good functioning of the network, and isn't really a security risk.

**Comment by infa-ddeore** [comment]
I am talking about this rule, is this not a security issue allowing for 0.0.0.0/0 ?

![image](https://user-images.githubusercontent.com/39782583/85928233-0d578c00-b8c9-11ea-9055-e875b08a593a.png)

I will read through the links you provided.

**Comment by TBBle** [comment]
That's right, that's not a security issue, it's needed for your traffic to actually flow correctly and with good performance, as that message is sent to you by intermediate routers when you are sending too-large packets, that will otherwise be dropped.

There's a useful diagram of what happens if you block that message under ["ICMP MESSAGES BEING BLOCKED"](https://www.fir3net.com/Networking/Protocols/path-mtu-path-mtu-black-holes.html).

**Comment by infa-ddeore** [comment]
I am trying to understand in what case the problem would occur.

If client is accessing a service over ELB and ELB is responding with higher MSS then intermediate routers will send ICMP response to ELB?

`loadBalancerSourceRanges` are applied to TCP as well as ICMP rule, so there needs to be separate annotation for ICMP since you recommend it to keep open regardless of other ports' restriction.

**Comment by TBBle** [comment]
You've identified the problem, yes. I'm not sure if there's some magic in the Security Group that recognises an ICMP type 3 packet as being sent on behalf of an allowed source address, i.e. parsing the type 3 header which includes the data about the packet being responded to. I could easily believe such magic exists, because this'd be pretty easy to get wrong if you're blindly applying IP restrictions.

Otherwise this is indeed a bug in the setup, that it will reject Fragmentation Required responses when `loadBalancerSourceRanges` is in use, as they will not come from an allowed IP address.

This probably needs to be tested by someone who is on an MTU-constrained connection, which many home Internet users are (due to PPPoE and related protocols) but equipment in a datacentre is generally not.

**Comment by infa-sathkuma** [comment]
I am also looking for the scenario where the PMTU to work with the ELB . AWS security group has a specific rule for ICMP type 3 DF set .
MSS is a negotiated value. We can see that exchange in wireshark capture. The upper bound of the advertised TCP MSS is most likely the MTU of the first hop route. Now what makes the MTU higher ? the biggest payload element is TCP MSS, which would have been sent over with SYN packet. 
most of the security scans are flagging ICMP 0.0.0.0/0 not sure if it looks at type 3.

**Comment by TBBle** [comment]
[MSS isn't negotiated](https://networkengineering.stackexchange.com/a/33575), it's simply announced by each end as to what their receive-size MSS, for segments going to that end. It defaults to 'MTU - 20 (IP Header minimum size) - 20 (TCP header minimum size)'.

However, MSS is only _ideally_ set to be small-enough to fit in a single packet, and PMTUD has [historically interefered with this as much as it's helped](https://tools.ietf.org/html/rfc2923) (See 2.3.).

So I would ignore the MSS here, it's not really relevant to the discussion, as a single TCP segment can be split across multiple IP datagrams without issue.

----

The necessity of "destination unreachable: needed fragmentation" here is that you _immediately_ get back a response to know that the TCP layer will have to resend, and the IP layer now knows that this resend and and any future segments of sufficient size should be fragmented locally before transmission.

Without that message, a narrow-MTU link between your NLB will cause do-not-fragment packets to simply disappear when they are too large. TCP will resend, and those will disappear too. This is the stalling problem from the original bug report, and also a [historically known issue](https://tools.ietf.org/html/rfc2923) (See 2.1.).
