### ISSUE TITLE
Adding tag annotations on service manifest for NLB does not trigger update on AWS

### ISSUE THREAD

**Issue by HoJinKind** [kubernetes/cloud-provider-aws#113]
BUG REPORT:
/kind bug

What happened:
Adding this annotation to an existing service: {"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}} did not trigger an update on AWS ELB (no new tags) if it is a NLB.

What you expected to happen:
Expected to see those 2 new tags under the existing ELB: team=devops,env=qa

How to reproduce it (as minimally and precisely as possible):

Create a service without annotation
Add the annotation {"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}}
No tags on AWS
Anything else we need to know?:
Creating a new service WITH the annotation will create the expected tags on AWS.

Environment:

Kubernetes version (use kubectl version): 1.18.3
Cloud provider or hardware configuration**: AWS
OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
Install tools:
Others: Using Kops

**Comment by damerakd** [comment]
Hello, I also faced the same issue where tags are not being updated for the service when using the annotation aws-load-balancer-additional-resource-tags if it is NLB. However they are being added to the Loadbalancer if it is CLB. 

So, I looked into the code responsible for ensuring an NLB through service spec of type LoadBalancer. Firstly, method responsible for ensuring a NLB is ensureLoadbalancerv2() method [1]. If we notice here [2], before the load balancer is being provisioned, it fetches the tags from annotations using getLoadBalancerAdditionalTags() method and adds them to part of createRequest [3] inside if block which is used finally to create a load balancer [4].

Note that the execution comes into the if block [5] only if the condition (if loadBalancer == nil) is met, which indicates only the first time when a new load balancer is being provisioned.

However if the load balancer is already created, I do not see any action to apply added or removed tags that can be decided by simply comparing the output of describe tags on the NLB and getLoadBalancerAdditionalTags() is not being called from within the else block [6] which is responsible for syncing the changes if load balancer already exists.

Implementation of getLoadBalancerAdditionalTags() method can be found here [7] which is responsible for converting the comma separated list of key-value pairs in the ServiceAnnotationLoadBalancerAdditionalTags annotation and returning it as a map. ServiceAnnotationLoadBalancerAdditionalTags annotation is a constant for service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags [8]

This led me to believe that the reason on why the tags are not being updated is due to no underlying code to handle this scenario. Since the tag creation method is being called only during creation of load balancer for the first time, the workaround would be to create the new service which would work as all the tags are fetched by getLoadBalancerAdditionalTags() method.

=======================
***** Why tags are being updated for CLB classic load balancer *****

Now coming into the reason on why it is working for load balancer of type CLB, the method responsible for ensuring a CLB load balancer is ensureLoadbalancer()[9]. Then, getLoadBalancerAdditionalTags() method is being called [10] inside if block and then subsequently the createRequest and CreateLoadbalancer methods. This is responsible for adding tags to the load balancer during creation time.

However, in the else block [11] which is responsible for syncing changes to the load balancer, I see that getLoadBalancerAdditionalTags() method is again being called [12] which explains why the CLB was able to update the tags and not NLB when changes were made to the annotation.

    {
        // Add additional tags
        klog.V(2).Infof("Creating additional load balancer tags for %s", loadBalancerName)
        tags := getLoadBalancerAdditionalTags(annotations)
        if len(tags) > 0 {
            err := c.addLoadBalancerTags(loadBalancerName, tags)
            if err != nil {
                return nil, fmt.Errorf("unable to create additional load balancer tags: %v", err)
            }
        }
    }
========================

References
[1] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L117
[2] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L126
[3] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L154
[4] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L160
[5] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L131-L173
[6] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L174-L354
[7] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L90
[8] https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L188
[9] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L901
[10] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L934
[11] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L968-L1168
[12] https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L1120-L1130

**Comment by damerakd** [comment]
Additionally, I was able to notice that the tags are not being removed from the LoadBalancer during update to the Service or the annotation is removed or the service is deleted for both the NLB and CLB LoadBalancers. **This one is important because eventually we reach the limit on number of tags for the load balancer and we would face new issues as a result**

==============
***** Why tags are not removed for CLB and NLB when the annotation is deleted by updating the service *****

-- For NLB, it is straight forward, as the getLoadBalancerAdditionalTags() method is not being called during syncing of the changes there is no code to handle this scenario. 

-- For CLB, I think the code is not taking into consideration the scenario of removing tags. As I do not see a logic to decide which tags needs to be removed or tags that needs to be added. The current logic is adding any tags that was defined on service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags without taking into consideration whether they exist or not.

========================

So, in my view, the listed below are the scenarios that are possible for service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags annotation.

---
|  | Annotation Specified | Annotation Specified |
|-|-|-|
|During initial Service Creation | Yes |  No|
|During Update | Modified/Removed |  Yes|
---

The code we currently have for ensuring CLB handles the scenario when initially there is no annotation specified in service spec and later during update if the annotation is given (because length of tags is greater than zero), CLB will be updated with the given tags.

It also handles the scenario where initially we create a service of type CLB using annotation, and later if we update the service with additional tags, the tags are updated but however the given existing tags are not reconciled. For example if we initially use the below annotation during service creation:

**service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: env=test,name=test-q6pv,project=inquiry**

All the above mentioned tags are added to the Classic Load Balancer. However if we update the service spec using the below annotation:

**service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: name=test-q6pv,project=inquiry,group=ADS**

We can notice that only the tag group=ADS is added to the load balancer, but the tag which is removed from annotation env=test is not reflected in the console.

=====================

I think the above behavior can be explained because of the below code:

    {
        // Add additional tags
        klog.V(2).Infof("Creating additional load balancer tags for %s", loadBalancerName)
        tags := getLoadBalancerAdditionalTags(annotations)
        if len(tags) > 0 {
            err := c.addLoadBalancerTags(loadBalancerName, tags)
            if err != nil {
                return nil, fmt.Errorf("unable to create additional load balancer tags: %v", err)
            }
        }
    }
During update, we are just considering the length of new tags for service and then calling the addLoadBalancerTags() [1] method which in turn is calling the AddTags() method available for ELB interface [2]. We are not reconciling the difference to the tags and then updating the load balancer accordingly.

***** Summary and workarounds *****

-- For LoadBalancer of type NLB through kubernetes service, tags can currently be used only during creation time using service annotations and cannot be used while updating the service. So, any tags you wish to have for the service would have to be specified during creation of the service.

-- For LoadBalancer of type CLB, tags can be used both while creation and also during updates to the service by making use of annotations.

-- For both NLB and CLB, removing the annotation "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags" from the service would not remove the already applied tags and they would have to be removed manually from the console after updating the service by removing the above annotation or they would be deleted when the service is deleted.

References
[1] https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2900
[2] https://github.com/kubernetes/kubernetes/blob/a6405451674428172956116b4c93710ac03ebddd/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L349

**Comment by luisamador** [comment]
I'm expriencing the same issue. It would be great to fix this issue. I can't update the tags on my NLB using the annotations discussed on this issue. Seems like an easy fix?

**Comment by nckturner** [comment]
@M00nF1sh @kishorj

**Comment by aSapien** [comment]
I'm experiencing the same issue

**Comment by zerog2k** [comment]
Curious also if anyone notices that in the case of CLB, the tags propagate to the LB resource (expected), but do not propagate to auto-created SG resource (unexpected)? (seems like a bug, and I'm willing to open a separate issue, if that's the correct route).

**Comment by calvinbui** [comment]
Same for me on v1.19 EKS with NLBs

**Comment by kuntalkumarbasu** [comment]
we are facing this issue with 1.20 as well

**Comment by niuzs-alan** [comment]
Same for idle

**Comment by Kyslik** [comment]
We are experiencing the same thing :(. Changing/updating `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` on service is not updating tags of NLB on EKS 1.19.

**Comment by nckturner** [comment]
/assign 

Will check if this needs to be cherry-picked from upstream.

**Comment by loliveiracodacy** [comment]
We're having a similar issue with 1.19 and clb.

First time the tags are applied correctly , but any further modifications are not synched to the load balancer, even though they are properly updated within the cluster resources (service and/or ingress).

**Comment by izinovik** [comment]
I'm deploying NGINX using custom Helm chart via terraform:
```
      deployments = {
        nginx = {
          replicas = 3
          service = {
            meta = {
              annotations = {
                "service.beta.kubernetes.io/aws-load-balancer-ssl-cert" = var.aws_acm_certificate_arn
                // It does not apply tags to existing NLBs
                "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags" = module.this.aws_tags_string_map

                #: external-dns
                "external-dns.alpha.kubernetes.io/enabled"  = "true"
                "external-dns.alpha.kubernetes.io/hostname" = var.gitlab_hostname
              }
            }
          }
        }
      }
```

**Comment by primeroz** [comment]
sad to see this closed by the Bot :(

**Comment by jasonbrianhall** [comment]
Please keep this open.  Have same issue.

**Comment by kishorj** [comment]
/reopen
@Kostavro, you mention issue with AWS Load Balancer Controller v2.4.5, could you share your service spec. It is likely you specified the annotation `service.beta.kubernetes.io/aws-load-balancer-type: nlb` and if so CCM is the controller provisioning NLB.

**Comment by Kostavro** [comment]
Hey @kishorj :)

Unfortunately that is not the case. Here are the annotations I am passing to the service:

```
service.beta.kubernetes.io/aws-load-balancer-type: "external"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes.io/service-name=gloo-system/gateway-proxy,kubernetes.io/cluster/{{ requiredEnv "EKS_CLUSTER_NAME" }}=owned
```

Here is the full spec of the service (via `-oyaml`):

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"kubernetes.io/service-name=gloo-system/gateway-proxy,kubernetes.io/cluster/eks-test-1=owned","service.beta.kubernetes.io/aws-load-balancer-internal":"true","service.beta.kubernetes.io/aws-load-balancer-nlb-target-type":"ip","service.beta.kubernetes.io/aws-load-balancer-type":"external"},"labels":{"app":"gloo","gateway-proxy-id":"gateway-proxy","gloo":"gateway-proxy"},"name":"gateway-proxy","namespace":"gloo-system"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080},{"name":"https","port":443,"protocol":"TCP","targetPort":8443}],"selector":{"gateway-proxy":"live","gateway-proxy-id":"gateway-proxy"},"type":"LoadBalancer"}}
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes.io/service-name=gloo-system/gateway-proxy,kubernetes.io/cluster/eks-test-1=owned
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
  creationTimestamp: "2023-01-11T10:55:54Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - service.k8s.aws/resources
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system
  resourceVersion: "522622"
  uid: 4f44dfed-05fa-46bc-9a9d-66f822b744a8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.59.219
  clusterIPs:
  - 172.20.59.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30234
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32425
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: k8s-gloosyst-gatewayp-xxx.elb.eu-central-1.amazonaws.com
```

**Comment by olemarkus** [comment]
This does look like an LBC issue and not a CCM issue.

**Comment by zerog2k** [comment]
> This does look like an LBC issue and not a CCM issue.

LBC would be AWS Load Balancer Controller, which looks at Ingress objects, correct?
This is a Service w/ type=LoadBalancer, which afaik is part of the aws cloud controller implementation?

**Comment by olemarkus** [comment]
Not when you are using the external load balancer type. See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/

**Comment by kishorj** [comment]
@Kostavro, the v2 version of the AWS load balancer controller ignores certain tags and the behavior introduced during the initial release to facilitate downgrade to the v1 version of the controller. Here is the list:
```
		"kubernetes.io/cluster/<CLUSTER_NAME>",
		"kubernetes.io/cluster-name",
		"kubernetes.io/namespace",
		"kubernetes.io/ingress-name",
		"kubernetes.io/service-name",
		"kubernetes.io/service-port",
		"ingress.k8s.aws/cluster",
```
For further details - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/a92e689dfe464f5b24784f398947e0fef31dc470/pkg/deploy/tracking/provider.go#L122

The v2 version of the LB controller doesn't set these tags. In addition, if they are set on the AWS resources externally, the controller leaves them in place. You can specify any other tags that are not used internally by the controller.

If you have further concerns, please file an issue in the AWS lb controller repo.

**Comment by VivinrajSundararaj** [comment]
Still facing the issue for NLB while adding additional tags using `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags`. Kindly help to fix the issue.

**Comment by HoJinKind** [comment]
hi sorry im not inolved in these work anymore. still an issue?

**Comment by lngoquy1** [comment]
We are still facing this issue, could you reopen this? The tags work for classic LBs, but not NLB.
