### ISSUE TITLE
Add support for ELB session stickiness 

### ISSUE THREAD

**Issue by jackivanov** [kubernetes/cloud-provider-aws#281]
**What would you like to be added**:
Annotation to enable ELB session stickiness 

**Why is this needed**: 
For applications that require cookie based sticky sessions

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

/kind feature

**Comment by jaypipes** [comment]
Hi @jackivanov :) I didn't realize you needed TCP-based sticky sessions from your original post.

I found these Q&As in the AWS Elastic Load Balancing [FAQ](https://aws.amazon.com/elasticloadbalancing/faqs/):

> Q: How do I decide which load balancer to select for my application?
>
> A: Elastic Load Balancing supports three types of load balancers. You can select the appropriate load balancer based on your application needs. If you need to load balance HTTP requests, we recommend you to use Application Load Balancer. For network/transport protocols (layer4 – TCP, UDP) load balancing, and for extreme performance/low latency applications we recommend using Network Load Balancer. If your application is built within the EC2 Classic network then you should use Classic Load Balancer.
> Q: Does a Classic Load Balancer have the same features and benefits as an Application Load Balancer?
> 
> A: While there is some overlap, there is no feature parity between the two types of load balancers. Application Load Balancers are the foundation of our application layer load-balancing platform for the future.

Which are the clearest signal I could find about switching away from CLB -> ALB/NLB.

May I ask if you are using TCP sticky sessions due to using websockets? If that is the case, you can configure ALB to support websockets over HTTP.

Best,
-jay

**Comment by jackivanov** [comment]
@jaypipes oh sorry for the confusion, we need sticky sessions for HTTP. We have an application that exposes 2 protocols - http and tcp. We need sticky sessions for HTTP only, because it's required by the application. Sticky sessions for http can be configured on a Classic ELB, meanwhile having another port in the TCP mode. Neither ALB nor NLB provides this functionality unfortunately, so there's no replacement at the moment.
