### ISSUE TITLE
Documentation missing for annotation `service.beta.kubernetes.io/aws-load-balancer-security-groups`

### ISSUE THREAD

**Issue by bhumijgupta** [kubernetes/cloud-provider-aws#326]
**What would you like to be added**:
In the docs for the controller (https://cloud-provider-aws.sigs.k8s.io/service_controller/), I cannot find the documentation for annotation `service.beta.kubernetes.io/aws-load-balancer-security-groups` but I see it being supported and used in the code

**Why is this needed**:
I was looking for this functionality and could not find it in the doc, I had to go through the code to find that this functionality exists

/kind feature

**Comment by neoakris** [comment]
/reopen
^-- I'm guessing this won't work since I'm not the post's author

@bhumijgupta Can this be reopened it's still an issue
https://cloud-provider-aws.sigs.k8s.io/service_controller/
^-- ctrl f this page for "service.beta.kubernetes.io/aws-load-balancer" = 21 entries

https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/aws/aws.go
^-- ctrl f this ancestral page for "const ServiceAnnotationLoadBalancer" = 22 entries
