### ISSUE TITLE
Support multiple route tables

### ISSUE THREAD

**Issue by DockToFuture** [kubernetes/cloud-provider-aws#432]
**What would you like to be added**:

I would like to be added support for multiple route tables.

**Why is this needed**:

This is needed in order to create an aws kubernetes cluster with multiple zones when the routing is done without an overlay. For each zone I have a separate route table and when I try to set the cluster up ccm returns the following error:

```
E0719 13:12:31.260618       1 route_controller.go:119] Couldn't reconcile node routes: error listing routes: found multiple matching AWS route tables for AWS cluster: shoot--core--aws-no-ov
```
After checking the code I saw that only one route table is [supported](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws_routes.go#L62) by cloud controller manager. 
It would be great if support for multiple route tables could be added. The setup works on all other cloud providers but not on aws due to the missing support of this feature.

/kind feature

**Comment by nckturner** [comment]
Sounds reasonable at first glance, but could I get you to provide more information about your desired set-up so I can play around and understand the limitation?  What CNI are you using?  What are you using to set up the cluster?

**Comment by ScheererJ** [comment]
We (@DockToFuture and me) are using [Gardener](https://gardener.cloud) to create the kubernetes clusters. It uses the [Gardener extension provider AWS](https://github.com/gardener/gardener-extension-provider-aws) to setup the infrastructure. You can find the terraform template [here](https://github.com/gardener/gardener-extension-provider-aws/blob/master/pkg/controller/infrastructure/templates/main.tpl.tf). Essentially, there is a cluster-global route table per cluster, which includes the kubernetes node cidr as local and the internet gateway as default route, and per availability zone there is another route table, which includes the kubernetes nodes cidr as local and a nat gateway as default gateway.
We use calico or cilium as CNIs, with calico being used in the majority of scenarios. As of now, we use overlay networks (IP-in-IP for calico and vxlan for cilium), but would like to get rid of them. Therefore, our goal is to use the cloud controller manager to create the corresponding routes for the per node pod cidrs in the infrastructure. It works for all other infrastructures we work on, e.g. Azure, GCP and OpenStack.

**Comment by jaypipes** [comment]
@DockToFuture pinging on this. Any way we can get a networking diagram for how Gardener requires underlying connectivity to look like?

**Comment by kon-angelo** [comment]
Hello @jaypipes ,
You can see an example diagram for one of the multizonal clusters we create in the following picture.

![graph](https://user-images.githubusercontent.com/68001306/197992856-555796e7-5e9d-48c1-b27f-efdf3d201eaa.svg)

Compared to the standard EKS Cluster a gardener cluster has the following setup:
* 3 subnets per zone. This is the equivalent to the public and private subnets(called `nodes_` in gardener) for an EKS cluster, with the addition of one more for internal loadbalancing purposes (called `private_` in gardener).
* One route table (named *main*) for all the public subnets. Public subnets have a NATGW and a route to the IGW.
* `nodes` subnets get their own route table with a route to their respective zones NAT GW.
The setup so far is very similar to what we see EKS to be using. 

The main differences are:
1. we are not confined to use the AWS CNI only, but also support Calico and Cilium as @ScheererJ mentioned. 
2. the pod CIDR ranges we use are not necessarily part of the VPC range.

Because of these differences, we cannot rely on native VPC routing (e.g like the secondary IPs for instances used by EKS) and we need each of the route tables used by the `nodes` subnets to be extended with routes that forward the traffic targeting specific pod IP ranges to their assigned node.
From what we can see, any setup that aims to provide multi-zonal support in AWS needs to use multiple subnets and by extension these subnets will need their own route table. This is why we think that it is a good idea to extend the already existing capability of the AWS CCM to properly work for these multi-zone setups.
