### ISSUE TITLE
Allow load balancer name to be provided via service annotation

### ISSUE THREAD

**Issue by mrf** [kubernetes/cloud-provider-aws#55]
**What would you like to be added**:
Would like to add an additional annotation type for the load balancer name.

**Why is this needed**:
Currently balancer can only be created with a machine-generated name making it very hard to distinguish in AWS if multiple balancers have been created within an account.

Additionally the DefaultLoadBalancerName from the cloud-provider package which is currently in use here has been deprecated and needs a replacement.

/kind feature

**Comment by randomvariable** [comment]
Discussion from cloud provider 2020/05/01:
Potentially have a new v2 API, but weary of a breaking change as would need to support the old and new API

/priority important-longterm

**Comment by justinsb** [comment]
There's also some related issues in k/k.  A good entrypoint is  https://github.com/kubernetes/kubernetes/issues/69293 , an AWS specific issue is https://github.com/kubernetes/kubernetes/issues/29789

**Comment by michaelajr** [comment]
Even a name `prefix` via annotation would be a good first step. And since the naming Go code adds the Service UUID and then truncs to 32 chars, we would not run into any length restrictions.

**Comment by ben-turner** [comment]
If this change is made, the ability to name target groups would also be great. Also, documentation on how the names are generated by default. From what I can tell, the names are always the same, which is a problem when running multiple clusters.

My use case is that something broke on AWS's end and there's a broken target group stuck in my account. I need to change the name so that I can create a new one.
