### ISSUE TITLE
Malformed provider ID crashes cloud-controller-manager

### ISSUE THREAD

**Issue by chewong** [kubernetes/cloud-provider-aws#604]
**What happened**:

```
E0416 22:04:28.488055      11 runtime.go:79] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"<node-name>\" on index \"instanceID\": error mapping node \"<node-name>\"'s provider ID \"foo://com-2351\" to instance ID: Invalid format for AWS instance (foo://com-2351)"} (unable to calculate an index entry for key "<node-name>" on index "instanceID": error mapping node "<node-name>"'s provider ID "foo://com-2351" to instance ID: Invalid format for AWS instance (foo://com-2351))
```

Users can self-DOS if they manually edit the node's provider ID to a malformed string. I am wondering if this is by design or we should ignore this error.

https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws.go#L853

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by kmala** [comment]
The provider ID is updated by the [k8s](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/cloud.go#L106) based on the instance ID returned by the CCM. So, the better way i think would be to skip the instance instead of failing. We can ignore instance with bad provider id similar to instances with no provider id https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws.go#L853

**Comment by mmerkes** [comment]
Is there any downside if we skip the instance? In the case where the provider ID is not set, the assumption is that eventually it will be. Obviously, we don't want to crash CCM is this is wrong, and I don't know if there's anything to do but ignore it.
