### ISSUE TITLE
Allow for hostnames other than private dns

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-aws#63]
**What would you like to be added**:
Does the out-of-tree AWS cloud provider allow for hostname overrides or at least hostnames that aren't the private DNS name? There's a few issues in kubernetes/kubernetes regarding limitations in the kubelet where it can only assign the private DNS name as a node name, it would be great if the out-of-tree provider allows for more flexiblity here without breaking anything.

Related: 
https://github.com/kubernetes/kubernetes/issues/54482
https://github.com/kubernetes/kubernetes/issues/52241

**Why is this needed**:
More descriptive node names are generally useful. 

/kind feature

**Comment by andrewsykim** [comment]
@justinsb @nckturner @M00nF1sh can you comment on if the out-of-tree provider will allow for hostnames aside from private DNS? I assumption is yes because we will be working with whatever hostname the kubelet (without --cloud-provider=aws) has already.

**Comment by nckturner** [comment]
I think we should allow for different hostnames--we have the same assumption in EKS, so I think the out of tree cloud provider would be a perfect place to add the flexibility, and we should remove those assumptions from EKS by the time we migrate to out-of-tree.

**Comment by edgan** [comment]
I implemented this on my own. The change is very minimal. The only thing what would probably change in an official patch would be the tag name.

http://cygnusx-1.org/kubernetes-aws-hostnames.patch

**Comment by schlitzered** [comment]
any news here, on an official solution?

**Comment by zanven42** [comment]
any chance of this being worked on?

**Comment by wongma7** [comment]
as of 1.23 alpha node names being equal to instance id is allowed by patch https://github.com/kubernetes/cloud-provider-aws/pull/286 which changed internal implementation  of
`func (c *Cloud) InstanceID(ctx context.Context, nodeName types.NodeName) (string, error) {`

Basically with in-tree cloudprovider the node name was restricted to privateDNS because that is what `CurrentNodeName ` returned.

With out-of-tree cloudprovider the node name is restricted by what InstanceID can derive instance id from. So we could build on the work of #286  to accept stuff like if the node name simply has prefix instance id or such depending on what people want.

**Comment by wongma7** [comment]
however the assumption that private dns == node name is deeply embedded in the v1 impelmentation (e.g. we found bug in route controller where breaking this assumption leads to spammed aws api requests which is obviously a bug ) https://github.com/kubernetes/cloud-provider-aws/pull/319 so it's not trivial to extend support for more node names, it needs lots of testing.

**Comment by olemarkus** [comment]
I think we can close this one now. See https://cloud-provider-aws.sigs.k8s.io/prerequisites/
