### ISSUE TITLE
Load balancer type is Classic, Is there any way i can configure like application or network ?

### ISSUE THREAD

**Issue by flyboy0808** [kubernetes/cloud-provider-aws#680]

**Comment by mmerkes** [comment]
Yes. You can read the EKS documentation for more information on using ALB or NLB:

* [ALB Ingress](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)
* [NLB Ingress](https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html)

The recommendation is that you use the [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller) instead of the cloud provider implementation as the cloud provider implementation is in maintenance mode only.
