### ISSUE TITLE
Cannot enable instance metadata access to tags due to tag format

### ISSUE THREAD

**Issue by adamacosta** [kubernetes/cloud-provider-aws#762]
**What happened**:

See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1785

If you deploy an ASG with the launch template set to allow instances access to tags via the metadata service, the API request to AWS will return an error:

```
InvalidRequestException: 'k8s.io/cluster-autoscaler/enabled' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\-+=,.@:]{1,255}), and must not be a reserved name ('.', '..', 'index')
```

Note this example is for autoscaler, but it's the same error for both cloud-provider-aws and cluster-autoscaler. The issue is simply having '/' in a tag.

**What you expected to happen**:

It should be possible to allow metadata access to tags when using CCM (or cluster-autoscaler or both).

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to deploy any ASG with more than 0 instances using the tag specifications from either cloud-provider-aws or cluster-autoscaler with metadata access to tags set to enabled. It is not necessary to actually install Kubernetes. Launching an instance at all fails.

**Anything else we need to know?**:

I'm guessing this is just a consequence of the fact that the metadata service lets you query "http://169.254.169.254/latest/meta-data/tags/instance/{tag-key}" and doesn't allow '/' in the tag key, even though this is valid for an AWS tag in general, because it gets interpreted by the API backend for hierarchical routing and can't be part of an API resource name. Their regex appears to be pretty close to the RFC 3986 path segment definition, removing '~', adding '+' and '=', and adding a 255 character limit.

This feels more like a bug on the part of AWS and they shouldn't allow '/' in tags at all, at least not for EC2 instances, but I'm fairly certain they won't care or do anything about it. Kubernetes projects associated with AWS, on the other hand, could at least not require tags that won't be allowed. I don't expect you'll do anything, either, given this is a fairly standard way of namespacing annotations in Kubernetes, but documentation could at least be added that metadata service access to tags isn't possible if you use cloud-provider-aws.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by cartermckinnon** [comment]
This is a documented limitation of tags-on-IMDS:
> If you enable instance tags in instance metadata, instance tag keys can only use letters (a-z, A-Z), numbers (0-9), and the following characters: `+ - = . , _ : @`. Instance tag keys can't contain spaces or `/`, and can't comprise only `.` (one period), `..` (two periods), or `_index`.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

I do not expect this to change.

/close not-planned

**Comment by adamacosta** [comment]
Yeah, so did you see I said in my report that I realize this is a limitation of tags on IMDS? I was suggesting you add documentation to the examples of how to use this provider saying you can't enable metadata tag access. I'm sure most people will figure that out anyway, but you'd be saving them a few minutes to a few hours of figuring it out. Making things a tiny bit easier on users is a pleasant thing developers can do to be friendly.

**Comment by cartermckinnon** [comment]
@adamacosta feel free to open a doc PR if you think it would help, probably should go in here: https://github.com/kubernetes/cloud-provider-aws/blob/master/docs/prerequisites.md

**Comment by gregorymkirk** [comment]
this is highly disappointing as the automatically generated tags for EKS break tags in metadata.  One feature in AWS breaking another feature does seem to be a bit odd.

**Comment by seanvaleo** [comment]
I'm now running into this after the automatically generated tags for EKS include illegal characters, and prevent enablement of instance tags in metadata (until manually changed).

**Comment by Edcox80** [comment]
key path

[Lease-Agreement-ID20250304.pdf](https://github.com/user-attachments/files/19625669/Lease-Agreement-ID20250304.pdf)

**Comment by benjimin** [comment]
This is super-annoying, that IMDS breaks EC2 support for broader tag formats.

Many k8s workloads expect nodes to be able to have labels/taints (that sometimes include slashes and dashes). Generally this content must be supplied in args to `kubelet`. But `cluster-autoscaler` (often practically part of the k8s control plane) also requires ASGs to have tags in a special format (which always requires using slashes and dashes), including for `cluster-autoscaler` to predict what node labels/taints the generated instances (from each ASG) will express. Since the EC2 instances typically inherit tags from the ASG, and tags can be exposed in the IMDS, it would be ideal if the instance could glean those special tags directly (through the IMDS) and pass them straight to `kubelet`. But this isn't possible; incompatibility with the format of `cluster-autoscaler` tags prevents the ASG from spawning EC2 instances if the IMDS is set to expose tags.

Instead, some other channel is needed to transfer the labels/taints, from ASG to `kubelet`. 
* One work-around is to customise the launch template's cloudinit _userdata_ (by maintaining a separate launch template for each individual ASG). This is a bit clunky, and invites inconsistencies between the ASG tags and `kubelet` args, which can confuse `cluster-autoscaler` (especially when deciding whether to scale up an ASG from zero) and potentially deadlock the cluster.
* Another work-around is to have the instance's IAM role grant it permissions to read inherited tags through AWS service APIs (rather than via the IMDS). This seems inefficient (since the IMDS is co-located with the generated instance as part of the hypervisor, but the API endpoint is an external service requiring more network traffic and authentication). It is also prone to violating least-privilege security principles (since processes on each node host will probably also be granted IAM privileges to inspect tags on other instances too). 
* Perhaps some other cloud controller component in k8s could be delegated to watch for new nodes joining the cluster, and apply labels/taints based on the tags of the underlying instance. Does such a utility already exist? 
* Another options is replacing `cluster-autoscaler` with Karpenter, which eschews ASGs entirely (and presumably does customise the _userdata_ for each instance), but brings it's own entirely different set of limitations..
