### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by der-eismann** [kubernetes/cloud-provider-aws#844]
**What would you like to be added**:

This project has a complete lack of documentation, which is a bit surprising to me when thinking about the importance to Kubernetes users on AWS. It really needs to be improved.

1. There's nowhere explained how to install it, apart from a hidden `kubectl apply` line in [getting started](https://cloud-provider-aws.sigs.k8s.io/getting_started/). I saw there is a release for a helm template, how do I use it? Do I have to download the tarball locally or is there a repo somewhere?
2. What exactly does it do and can I only use parts of it? In the readme it says  the following, however I don't want any NLBs or routes on AWS, all I care about are node labels and lifecycles. 
> The controller loops that are migrating out of the kube controller manager include the route controller, the service controller, the node controller, and the node lifecycle controller.   
3. In the [components section](https://cloud-provider-aws.sigs.k8s.io/service_controller/) it only mentions the service controller, what about the remaining components?
4. No explanation for the required IAM permissions. It says `Adjust these based on your needs`, but what are my needs? (see 2.)
5. Changelog in the docs is [broken as well](https://cloud-provider-aws.sigs.k8s.io/changelog/#387-fix-issues-in-tagging-controller-392-saurav-agarwalla) and unmaintained
6. Missing/wrong defaults in the `--help` section. `--allocate-node-cidrs` has no default value and `--controllers` states `'*' enables all on-by-default controllers` and then `Disabled-by-default controllers: tagging (default [*])`. So is tagging disabled or are all enabled by default as `*` would suggest?

**Why is this needed**:

So people can make use of it and know what they are doing.

/kind feature

**Comment by cartermckinnon** [comment]
Totally agree that the docs could be improved. In practice, this component is rarely deployed or configured by an end-user directly. For example, a tool like kOps will set it up for you, and it's included in EKS control planes. Documentation in this area hasn't been a priority as a result.

>  I don't want any NLBs or routes on AWS, all I care about are node labels and lifecycles.

It sounds like you just want the `cloud-node-controller` and `cloud-node-lifecycle-cpontroller`, which are implemented here: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cloud-provider/controllers

**Comment by der-eismann** [comment]
Rarely might be true, but it does happen :slightly_smiling_face: We started ages ago with our own bootstrapped kubelet and never migrated to a managed distribution like EKS, but it feels like we really should because stuff like this is becoming unmanageable. 

Anyhow, IMHO this software is a really important piece with Kubernetes on AWS and I think the docs deserve some more time and love.

**Comment by thefirstofthe300** [comment]
> Totally agree that the docs could be improved. In practice, this component is rarely deployed or configured by an end-user directly. For example, a tool like kOps will set it up for you, and it's included in EKS control planes. Documentation in this area hasn't been a priority as a result.

With CAPI, the exact opposite is true. CAPI does not provide any out of the box AWS cloud controller manager configuration as CAPI is meant to be a build your own cluster type project. I'm trying to get an AWS cluster stood up with Flannel and I'm suspecting my issues with DNS are caused by the coredns pods having an IP address which the VPC does not know how to route.

**Comment by et304383** [comment]
I cannot believe this isn't the number one upvoted issue.  The documentation (or lack thereof) is appalling and quite frankly embarrassing considering this is a critical component if you want to use K8s 1.27+.

**Comment by 2rs2ts** [comment]
<img width="425" alt="Image" src="https://github.com/user-attachments/assets/67cb7a41-035d-40cd-9a04-53f4ebfe7b39" />

No offense intended here, but this is the kind of screenshot that bosses I've had in the past would fire me for if I was responsible for causing them.

Also,

> In practice, this component is rarely deployed or configured by an end-user directly. For example, a tool like kOps will set it up for you, and it's included in EKS control planes.

So the people who work on kOps and who work at Amazon on EKS just don't need docs? Surely when those teams get new members, they have problems with those new members needing to be brought up to speed since there are no docs (and just reading the source isn't helpful, since the cloud provider framework relies far too much on code flows that symbol analyzers can't follow.)
