### ISSUE TITLE
Where is the latest documentation for this? 

### ISSUE THREAD

**Issue by SaltedEggIndomee** [kubernetes/cloud-provider-aws#86]
I've been trying for weeks to set up a vanilla Kubernetes cluster on AWS and still unable to pinpoint an official and latest tutorial to use this plugin.

Every guide on the internet uses `--cloud-provider=aws` flag, which we know will be deprecated very soon.

Also, on the half-baked instructions in this GitHub README, it says : 
> The flag --cloud-provider=external needs to be passed to kubelet, kube-apiserver, and kube-controller-manager.

But when you look at Kubernetes official documentation at https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/ : 
> kube-apiserver and kube-controller-manager MUST NOT specify the --cloud-provider flag.

So which is it??

**Comment by mikejoh** [comment]
Not that it's related to `cloud-provider-aws` documentation but to your observation regarding the docs and how and when the `--cloud-provider` flag should be not used/used: https://github.com/kubernetes/website/issues/20137

**Comment by zimmertr** [comment]
Hi, I would also be interested in this. I'm trying to put together a Kubeadm-based cluster on AWS at the moment and struggling to get the Cloud Provider integration to advance beyond my worker nodes being tainted with `node.cloudprovider.kubernetes.io/uninitialized`

**Comment by zimmertr** [comment]
Got this squared away thanks to the help of @andrewsykim. 

I had to make a few changes. First of all, if you look in the [manifests](https://github.com/kubernetes/cloud-provider-aws/tree/master/manifests) directory on the root of the repo there is a DaemonSet and an RBAC schema. These both need to be deployed and operational on your cluster for your nodes to be _initialized_. 

You'll notice that the DaemonSet doesn't have an [image reference](https://github.com/kubernetes/cloud-provider-aws/blob/6a14c81191aaebcfb60b24ca3445774ffb9f9254/manifests/aws-cloud-controller-manager-daemonset.yaml#L31). This is because the AWS Cloud Controller Manager isn't officially publicly hosted yet. You'll need to build it yourself or use one on DockerHub. [Here's](https://hub.docker.com/r/zimmertr/aws-cloud-controller-manager) the one I made from the newest commit from three days ago.

You might also notice that there is an `--cloud-provider=aws` argument passed to the container despite being the `external` provisioner. This _is_ intentional. 

Lastly, you'll need to ensure that all of your EC2 instances have this tag: `KubernetesCluster = var.K8S_CLUSTER_NAME` where `var.K8S_CLUSTER_NAME` is the name of your cluster.

**Comment by andrewsykim** [comment]
Looking for feedback on what the documentation site should look like https://github.com/kubernetes/cloud-provider-aws/pull/102

**Comment by andrewsykim** [comment]
We have a docs site here https://cloud-provider-aws.sigs.k8s.io/ but we need help with content

**Comment by nckturner** [comment]
We are in the process of updating the docs and adding a new docs site. I'll keep this issue updated.

**Comment by nckturner** [comment]
Follow progress here: 
https://kubernetes.github.io/cloud-provider-aws/

Also the README has been updated: https://github.com/kubernetes/cloud-provider-aws/blob/master/README.md but ideally that information should be included in the home page of the docs site too.

**Comment by nckturner** [comment]
Documentation will be available here going forward: https://cloud-provider-aws.sigs.k8s.io/

We will continue working on the docs, but I think we've made enough initial progress that I can close this issue.  Please feel free to open specific issues if you feel certain areas are lacking documentation.
